"""empty message

Revision ID: 78353fab6ed1
Revises: dc2a6d460a07
Create Date: 2022-09-17 06:23:53.657309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78353fab6ed1'
down_revision = 'dc2a6d460a07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_image', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar_image')
    # ### end Alembic commands ###
